defaults:
  - dataset: libero

# Model selection: 'dreamer' or 'simple'
model_type: 'simple'

experiment:
  name: mini_grp_simple
  project: mini-grp
  description: "SimpleWorldModel that predicts pose and reward from pose and actions"

# Model configuration for SimpleWorldModel
model: 
  type: "simple"
  hidden_dim: 256

batch_size: 256
max_block_size: 16
vocab_size: 32
n_patches: 8
patch_size: 8
max_iters: 25000
eval_interval: 100
learning_rate: 3e-4
lr_schedule: linear
eval_iters: 5
policy:
  action_stacking: 1
  obs_stacking: 1
  use_image_augmentations: false
  dtype: 'float32'
  use_pose_data: 1
  random_masking_enabled: false
  use_last_action: false
  add_noise_to_state: true
  state_noise_std: 0.01

testing: false
eval_vid_iters: 2500
gradient_accumulation_steps: 1

simEval: ["libero"]
sim:
  eval_episodes: 1
  eval_tasks: [0,1]
  episode length: 500
  task_set: "libero_spatial"
  libero_init_state_file: "/openvla/experiments/robot/libero/libero_spatial_init_states_and_goals.hdf"
  libero_init_state_hf_repo: "gberseth/libero_spatial_init_states"

r_seed: 1337
