defaults:
  - dataset: fast


experiment:
  name: mini_grp
  project: mini-grp
  description: "simple env with 64pix images and pose data"

# Model type: "transformer" or "convnet" or "dataset" or "dense"
model: 
  type: "transformer"

batch_size: 256 # how many independent sequences will we process in parallel?
max_block_size: 16 ## Tokens for langauge processing
vocab_size: 32 ## Will be overidden by code
n_patches: 8
patch_size: 8
max_iters: 25000
eval_interval: 100 # How often to run eval over the validation set
learning_rate: 3e-4
lr_schedule: linear ## ['inverse_sqrt', 'linear']
eval_iters: 5
policy:
  action_stacking: 1
  obs_stacking: 1
  use_image_augmentations: false
  dtype: 'float32'
  use_pose_data: 1
  random_masking_enabled: false  # Set to false to skip random masking, true to enable it
  use_last_action: false  # New flag to indicate whether to use last action as input
  add_noise_to_state: true  # New flag to indicate whether to add noise to state
  state_noise_std: 0.01  # Standard deviation of the noise to be added

testing: false
eval_vid_iters: 2500
gradient_accumulation_steps: 1

simEval: [] # "simpler_env" or "libero"
sim:
  eval_episodes: 1
  eval_tasks: [0]  # which tasks to eval on
  episode length: 500
  task_set: "libero_spatial"
  libero_init_state_file: "/openvla/experiments/robot/libero/libero_spatial_init_states_and_goals.hdf" # Path to HDF5 file containing initial states for LIBERO tasks.
  libero_init_state_hf_repo: "gberseth/libero_spatial_init_states" # Dataset key within the HDF5 file for LIBERO initial states.

# ------------

r_seed: 1337
device: "cuda"
n_embd: 512
n_head: 16
n_blocks: 4
dropout: 0.2
action_dim: 7
load_action_bounds: true


## Model hyperparameters
image_shape: [64, 64, 3]
data_shuffel_interval: 1000 ## How often to reshuffle the data buffer, grabbing new random sequences from the cloud.

profiler:
  enable: false
  params:
    # record_shapes: true
    profile_memory: true
    with_stack: true
    use_cuda: true